const SLIDESHOW_PHOTO_Z_INDEX = 0;

export const SLIDESHOW_UI_Z_INDEX = SLIDESHOW_PHOTO_Z_INDEX + 2;
export const SLIDESHOW_INSET_SHADOW_Z_INDEX = SLIDESHOW_PHOTO_Z_INDEX + 1;
// SLIDESHOW_PHOTO_Z_INDEX
export const SLIDESHOW_PHOTO_BORDER_TEXTURE_Z_INDEX = SLIDESHOW_PHOTO_Z_INDEX - 1;
export const SLIDESHOW_PHOTO_BORDER_Z_INDEX = SLIDESHOW_PHOTO_Z_INDEX - 2;