#!/bin/sh
rm -rf out # delete current local build
npm run sync-db # sync the databases
npm run build # build the site
neocities delete _next # remove the stale _next folder from neocities
neocities push out # upload site build
npm run prune-neocities-files
